### ISSUE TITLE
I don't understand how MSF indexing works.

### ISSUE THREAD

**Issue by i30817** [Manorhos/imageparse#7]
I can _guess_ that in LBA indexing, the 'block' is supposed to be equivalent to a 'sector' or maybe a multiple, since you iterate over all of the disc while increasing lba one by one.

But i did notice that if you use MsfIndex.from_lba when you do:
```
>>> MsfIndex.from_lba(9)
MsfIndex(0,0,9)
>>> MsfIndex.from_lba(10)
MsfIndex(0,0,16)
```
There is a jump, which could represent '>10 frames' should use seconds' - which doesn't happen here, and since `MsfIndex(0,1,0).to_lba() == 75` is probably a wrong idea anyway. Or could maybe represent 'msf actually uses hexadecimal digits' since '10h==16i', in which case i have to change the signature.

But you can:
```
>>> MsfIndex(0,0,10).to_lba()
10
```

So what's the bug here?

**Comment by Manorhos** [comment]
Hey, I got pretty busy last year and forgot about this for a while...
If you're still interested in what happened here:

From how it behaves, I'd guess you used `MsfIndex::to_bcd_values()` to display what's in it, see https://en.wikipedia.org/wiki/Binary-coded_decimal.
10 becomes 0x10, which is 16 in hexadecimal.
To be honest, I thought it would've been possible to decompose the `MsfIndex` tuple struct using pattern matching to get the (m,s,f) parts, but since the fields are private, that wasn't actually possible.

I've now added a `MsfIndex::to_raw_values()` method so one can get the inner value without it getting converted to BCD.
